language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
  - php: nightly
  fast_finish: true

before_script:
  - composer install --prefer-source --no-interaction

script: vendor/bin/phpunit
